[package]
name = "query_executor"
version = "0.1.0"
authors = ["Alex Dukhno <alex.dukhno@icloud.com>"]
edition = "2018"
publish = false

[dependencies]
ast = { path = "../../ast" }
binary = { path = "../../../data/binary" }
connection = { path = "../../../server/connection" }
constraints = { path = "../../constraints_deprecated" }
data_manager = { path = "../../catalog_deprecated/data_manager" }
expr_eval = { path = "../expr_eval" }
meta_def = { path = "../../../meta_def" }
plan = { path = "../../query_planning_deprecated/plan" }
pg_model = { path = "../../../server/pg_model" }
pg_wire = "0.5.0"
repr = { path = "../../../repr" }
sql_model = { path = "../../sql_model" }

bigdecimal = { version = "0.2.0", features = ["string-only"] }
futures-lite = "1.11.3"
log = "0.4.11"
sql_ast = { path = "../../../query_parsing/sql-ast" }

[dev-dependencies]
rstest = "0.6.4"
tempfile = "3.1.0"
