[package]
name = "typed_queries"
version = "0.1.0"
authors = ["Alex Dukhno <alex.dukhno@icloud.com>"]
edition = "2018"
publish = false

[dependencies]
definition = { path = "../../definition" }
typed_tree = { path = "../typed_tree" }
