[package]
name = "node"
version = "0.1.0"
authors = ["Alex Dukhno <alex.dukhno@icloud.com>"]
edition = "2018"
publish = false

[lib]
name = "node"

[[bin]]
name = "database"
path = "src/bin.rs"

[dependencies]
sql_ast = { path = "../../query_parsing/sql-ast" }
analysis_tree = { path = "../../query_analysis/tree" }
binder = { path = "../../deprecated/binder_deprecated" }
catalog = { path = "../../data_definition/catalog" }
connection = { path = "../connection" }
data_manager = { path = "../../deprecated/catalog_deprecated/data_manager" }
definition_operations = { path = "../../data_definition/definition_operations" }
description = { path = "../../deprecated/query_analysis_deprecated/description" }
parser = { path = "../../query_parsing/parser" }
pg_model = { path = "../pg_model" }
plan = { path = "../../deprecated/query_planning_deprecated/plan" }
pg_wire = "0.5.0"
schema_planner = { path = "../../data_definition/schema_planner" }
query_analyzer = { path = "../../query_analysis/query_analyzer" }
query_analyzer_old = { path = "../../deprecated/query_analysis_deprecated/query_analyzer_old" }
query_executor = { path = "../../deprecated/query_execution_deprecated/query_executor" }
query_planner = { path = "../../deprecated/query_planning_deprecated/query_planner" }
schema_executor = { path = "../../data_definition/schema_executor" }
types = { path = "../../types" }

async-executor = "1.4.0"
async-dup = "1.2.1"
async-io = "1.3.1"
blocking = "1.0.0"
bigdecimal = { version = "0.2.0", features = ["string-only"] }
futures-lite = "1.11.3"
itertools = "0.10.0"
log = "0.4.8"
simple_logger = { version = "1.10.0" }

[dev-dependencies]
rstest = "0.6.4"
