[package]
name = "node"
version = "0.1.0"
authors = ["Alex Dukhno <alex.dukhno@icloud.com>"]
edition = "2018"
publish = false

[lib]
name = "node"

[[bin]]
name = "isomorphicdb"
path = "src/bin.rs"

[dependencies]
catalog = { path = "../../data/catalog" }
connection = { path = "../connection" }
data_definition_operations = { path = "../../data_definition/operations" }
parser = { path = "../../query_parsing/parser" }
pg_model = { path = "../pg_model" }
pg_wire = "0.5.0"
query_analyzer = { path = "../../query_analyzer" }
schema_planner = { path = "../../data/schema_planner" }
sql_ast = { path = "../../query_parsing/sql-ast" }
types = { path = "../../entities/types" }
query_processing_type_check = { path = "../../query_processing/type_check" }
query_processing_type_inference = { path = "../../query_processing/type_inference" }
query_processing_type_coercion = { path = "../../query_processing/type_coercion" }
data_manipulation_query_result = { path = "../../data_manipulation/query_result" }
data_manipulation_untyped_queries = { path = "../../data_manipulation/untyped_queries" }
data_manipulation_typed_tree = { path = "../../data_manipulation/typed_tree" }
data_manipulation_typed_queries = { path = "../../data_manipulation/typed_queries" }
data_manipulation_operators = { path = "../../data_manipulation/operators" }
write_query_executor = { path = "../../write_query/executor" }
read_query_executor = { path = "../../read_query/executor" }
read_query_planner = { path = "../../read_query/planner" }

# deprecated modules
binder = { path = "../../deprecated/binder_deprecated" }
data_manager = { path = "../../deprecated/catalog_deprecated/data_manager" }
description = { path = "../../deprecated/query_analysis_deprecated/description" }
plan = { path = "../../deprecated/query_planning_deprecated/plan" }
query_analyzer_old = { path = "../../deprecated/query_analysis_deprecated/query_analyzer_old" }
query_executor = { path = "../../deprecated/query_execution_deprecated/query_executor" }
deprecated_query_planner = { path = "../../deprecated/query_planning_deprecated/query_planner" }
schema_executor = { path = "../../deprecated/schema_executor" }

async-executor = "1.4.0"
async-dup = "1.2.1"
async-io = "1.3.1"
blocking = "1.0.0"
bigdecimal = { version = "0.2.0", features = ["string-only"] }
futures-lite = "1.11.3"
itertools = "0.10.0"
log = "0.4.13"
simple_logger = { version = "1.10.0" }

[dev-dependencies]
rstest = "0.6.4"
