[package]
name = "data_definition_execution_plan"
version = "0.1.0"
authors = ["Alex Dukhno <alex.dukhno@icloud.com>"]
edition = "2018"
publish = false

[dependencies]
definition = { path = "../../../definition" }
types = { path = "../../../types" }

query_response = { path = "../../../postgre_sql/query_response" }
