[package]
name = "node"
version = "0.1.0"
authors = ["Alex Dukhno <alex.dukhno@icloud.com>"]
edition = "2018"
publish = false

[lib]
name = "node"

[[bin]]
name = "isomorphicdb"
path = "src/bin.rs"

[dependencies]
catalog = { path = "../../catalog" }
connection = { path = "../connection" }
data_scalar = { path = "../../data/scalar" }
data_definition_execution_plan = { path = "../../data_definition/execution_plan" }
parser = { path = "../../query_parsing/parser" }
pg_model = { path = "../pg_model" }
pg_result = { path = "../../pg_result" }
pg_wire = "0.5.0"
query_analyzer = { path = "../../query_analyzer" }
query_planner = { path = "../../query_planner" }
sql_ast = { path = "../../query_parsing/sql-ast" }
types = { path = "../../entities/types" }
query_processing_type_check = { path = "../../query_processing/type_check" }
query_processing_type_inference = { path = "../../query_processing/type_inference" }
query_processing_type_coercion = { path = "../../query_processing/type_coercion" }
data_manipulation_query_result = { path = "../../data_manipulation/query_result" }
data_manipulation_untyped_queries = { path = "../../data_manipulation/untyped_queries" }
data_manipulation_typed_tree = { path = "../../data_manipulation/typed_tree" }
data_manipulation_typed_queries = { path = "../../data_manipulation/typed_queries" }
data_manipulation_operators = { path = "../../data_manipulation/operators" }
data_manipulation_query_plan = { path = "../../data_manipulation/query_plan" }

async-executor = "1.4.0"
async-dup = "1.2.1"
async-io = "1.3.1"
blocking = "1.0.0"
bigdecimal = { version = "0.2.0", features = ["string-only"] }
futures-lite = "1.11.3"
itertools = "0.10.0"
log = "0.4.14"
simple_logger = { version = "1.10.0" }

[dev-dependencies]
rstest = "0.6.4"
