[package]
name = "query_analyzer"
version = "0.1.0"
authors = ["Alex Dukhno <alex.dukhno@icloud.com>"]
edition = "2018"
publish = false

[dependencies]
catalog = { path = "../catalog" }
data_definition_execution_plan = { path = "../data_definition/execution_plan" }
untyped_queries = { path = "../../inter_reprs/untyped_queries" }
operators = { path = "../../inter_reprs/operators" }
untyped_tree = { path = "../../inter_reprs/untyped_tree" }
data_manipulation_untyped_tree_builder = { path = "../data_manipulation/untyped_tree_builder" }
definition = { path = "../../definition" }
query_ast = { path = "../../inter_reprs/query_ast" }
query_response = { path = "../../postgre_sql/query_response" }
types = { path = "../../types" }
storage = { path = "../../storage" }

bigdecimal = { version = "0.2.0", features = ["string-only"] }
log = "0.4.14"

[dev-dependencies]
simple_logger = { version = "1.10.0", default-features = false }
data_definition_execution_plan = { path = "../data_definition/execution_plan" }
