[workspace]
members = [
    "src/ast",
    "src/binary",
    "src/constraints",
    "src/data_manager",
    "src/expr_eval",
    "src/kernel",
    "src/node",
    "src/protocol",
    "src/query_planner",
    "src/sql_engine",
    "src/sql_model",
]
