[workspace]
members = [
    "deprecated/ast", # TODO: should be removed after operation tree rewrite
    "data_definition/binary",
    "deprecated/binder_deprecated",
    "data_definition/catalog",
    "deprecated/constraints_deprecated",
    "server/connection",
    "deprecated/catalog_deprecated/data_manager",
    "data_definition/definition_operations",
    "deprecated/query_analysis_deprecated/description", # TODO: should be removed after operation tree rewrite
    "deprecated/query_execution_deprecated/expr_eval", # TODO: should be removed after operation tree rewrite
    "meta_def",
    "server/node",
    "server/pg_model",
    "deprecated/query_planning_deprecated/plan",
    "query_analysis/expr_operators",
    "query_analysis/query_analyzer",
    "deprecated/query_analysis_deprecated/query_analyzer_old", # TODO: should be removed after operation tree rewrite
    "query_analysis/tree",
    "deprecated/query_execution_deprecated/query_executor",
    "deprecated/query_planning_deprecated/query_planner",
    "repr",
    "deprecated/schema_executor",
    "data_definition/schema_planner",
    "deprecated/sql_model", # TODO: should be removed after operation tree rewrite
    "deprecated/catalog_deprecated/storage",
    "types",
    "query_parsing/sql-ast",
    "query_parsing/parser",
]
