[workspace]
members = [
    "data/binary",
    "data/catalog",
    "data/definition_operations",
    "data/schema_planner",
    "deprecated/ast",
    "deprecated/binder_deprecated",
    "deprecated/catalog_deprecated/data_manager",
    "deprecated/catalog_deprecated/storage",
    "deprecated/constraints_deprecated",
    "deprecated/query_analysis_deprecated/description",
    "deprecated/query_analysis_deprecated/query_analyzer_old",
    "deprecated/query_execution_deprecated/expr_eval",
    "deprecated/query_execution_deprecated/query_executor",
    "deprecated/query_planning_deprecated/plan",
    "deprecated/query_planning_deprecated/query_planner",
    "deprecated/schema_executor",
    "deprecated/sql_model",
    "meta_def",
    "query_analysis/expr_operators",
    "query_analysis/query_analyzer",
    "query_analysis/tree",
    "query_parsing/parser",
    "query_parsing/sql-ast",
    "repr",
    "server/connection",
    "server/pg_model",
    "server/node",
    "types",
    "write_query/executor",
]
