[workspace]
members = [
    "src/ast",
    "src/binary",
    "src/binder",
    "src/constraints",
    "src/data_manager",
    "src/description",
    "src/expr_eval",
    "src/kernel",
    "src/node",
    "src/protocol",
    "src/parser",
    "src/plan",
    "src/repr",
    "src/query_analyzer",
    "src/query_planner",
    "src/query_executor",
    "src/sql_model",
    "src/storage",
]
