[workspace]
members = [
    "data/binary",
    "data/catalog",
    "data/schema_planner",
    "data_definition/operations",
    "data_definition/execution_plan",
    "data_manipulation/operators",
    "data_manipulation/query_result",
    "data_manipulation/typed_queries",
    "data_manipulation/typed_tree",
    "data_manipulation/untyped_queries",
    "data_manipulation/untyped_tree",
    "entities/types",
    "entities/definition",
    "query_analyzer",
    "query_parsing/parser",
    "query_parsing/sql-ast",
    "query_processing/type_check",
    "query_processing/type_inference",
    "query_processing/type_coercion",
    "read_query/executor",
    "read_query/plan",
    "read_query/planner",
    "entities/repr",
    "server/connection",
    "server/pg_model",
    "server/node",
    "write_query/executor",
]
