[workspace]
members = [
    "data/binary",
    "data/catalog",
    "data/schema_planner",
    "data_definition/operations",
    "data_definition/execution_plan",
    "data_manipulation/operators",
    "data_manipulation/typed_queries",
    "data_manipulation/typed_tree",
    "data_manipulation/untyped_queries",
    "data_manipulation/untyped_tree",
    "deprecated/ast",
    "deprecated/binder_deprecated",
    "deprecated/catalog_deprecated/data_manager",
    "deprecated/catalog_deprecated/storage",
    "deprecated/constraints_deprecated",
    "deprecated/query_analysis_deprecated/description",
    "deprecated/query_analysis_deprecated/query_analyzer_old",
    "deprecated/query_execution_deprecated/expr_eval",
    "deprecated/query_execution_deprecated/query_executor",
    "deprecated/query_planning_deprecated/plan",
    "deprecated/query_planning_deprecated/query_planner",
    "deprecated/schema_executor",
    "deprecated/sql_model",
    "entities/types",
    "entities/definition",
    "meta_def",
    "query_analyzer",
    "query_parsing/parser",
    "query_parsing/sql-ast",
    "query_planner",
    "query_processing/type_check",
    "query_processing/type_inference",
    "query_processing/type_coercion",
    "entities/repr",
    "server/connection",
    "server/pg_model",
    "server/node",
    "write_query/executor",
]
