[workspace]
members = [
    "ast", # TODO: should be removed after operation tree rewrite
    "binary",
    "binder",
    "catalog",
    "constraints",
    "connection",
    "data_definition",
    "data_manager",
    "definition_operations",
    "description", # TODO: should be removed after operation tree rewrite
    "expr_eval", # TODO: should be removed after operation tree rewrite
    "meta_def",
    "node",
    "pg_model",
    "plan",
    "analysis/expr_operators",
    "analysis/query_analyzer",
    "analysis/query_analyzer_old", # TODO: should be removed after operation tree rewrite
    "analysis/tree",
    "query_executor",
    "query_planner",
    "repr",
    "schema_executor",
    "schema_planner",
    "sql_model", # TODO: should be removed after operation tree rewrite
    "storage",
    "types",
    "parsing/sql-ast",
    "parsing/parser",
]
