[package]
name = "isomorphicdb"
version = "0.1.0"
authors = ["Alex Dukhno <alex.dukhno@icloud.com>"]
edition = "2018"
publish = false

[dependencies]
# POSTGRES
pg_result = { path = "postgres/pg_result" }
pg_wire = "0.5.0"

#SQL-ENGINE
catalog = { path = "sql_engine/catalog" }
entities = { path = "sql_engine/entities" }
data_definition = { path = "sql_engine/data_definition" }
data_manipulation = { path = "sql_engine/data_manipulation" }
query_parsing = { path = "sql_engine/query_parsing" }
query_processing = { path = "sql_engine/query_processing" }
query_analyzer = { path = "sql_engine/query_analyzer" }
query_planner = { path = "sql_engine/query_planner" }

async-executor = "1.4.0"
async-dup = "1.2.1"
itertools = "0.10.0"
async-io = "1.3.1"
async-mutex = "1.4.0"
#TODO temporal to have ability to run ./local/code_coverage.sh
async-native-tls = { git = "https://github.com/alex-dukhno/async-native-tls.git", branch = "new-native-tls" }
async-trait = "0.1.42"
blocking = "1.0.0"
bigdecimal = { version = "0.2.0", features = ["string-only"] }
byteorder = "1.4.2"
futures-lite = "1.11.3"
log = "0.4.14"
simple_logger = { version = "1.10.0" }
rand = "0.7"

[dev-dependencies]
rstest = "0.6.4"
tempfile = "3.1.0"

#[workspace]
#exclude = ["sql_engine", "postgres", "etc", "docs"]

#[workspace]
#members = [
#    "src/catalog",
#    "src/data/binary",
#    "src/data/scalar",
#    "src/data_definition/execution_plan",
#    "src/data_manipulation/operators",
#    "src/data_manipulation/query_result",
#    "src/data_manipulation/query_plan",
#    "src/data_manipulation/typed_queries",
#    "src/data_manipulation/typed_tree",
#    "src/data_manipulation/typed_values",
#    "src/data_manipulation/untyped_queries",
#    "src/data_manipulation/untyped_tree",
#    "src/entities/types",
#    "src/entities/definition",
#    "src/query_analyzer",
#    "src/query_parsing/parser",
#    "src/query_parsing/sql-ast",
#    "src/query_planner",
#    "src/query_processing/type_check",
#    "src/query_processing/type_inference",
#    "src/query_processing/type_coercion",
#    "src/server/connection",
#    "src/server/pg_model",
#    "src/server/node",
##     TODO: to be extracted
#    "src/pg_result",
#]
