[bans]
multiple-versions = "deny"
skip-tree = [
    # getrandom v0.1.15
    #     ├── rand v0.7.3
    #     │   ├── fail v0.4.0
    #     │   │   └── storage
    #     │   ├── protocol v0.1.0
    #     │   └── tempfile v3.1.0
    #     └── rand_core v0.5.1
    #         └── rand v0.7.3 (*)
    #
    # getrandom v0.2.0
    #     └── const-random-macro v0.1.11
    #         └── const-random v0.1.11
    #             └── ahash v0.3.8
    #                 └── dashmap v3.11.10
    #                     ├── data_manager v0.1.0
    # protocol -> rand -> wasi
    { name = "getrandom" },
]

[licenses]
private = { ignore = true }
unlicensed = "deny"
confidence-threshold = 0.93
allow = [
    "Apache-2.0",
    "BSD-3-Clause",
    "MIT",
    "Zlib",
]
exceptions = [
    # smol use wepoll
    { allow = ["MPL-2.0"], name = "wepoll-sys" },
    { allow = ["MPL-2.0"], name = "colored" },
]

[sources]
unknown-git = "deny"
unknown-registry = "deny"
allow-git = [
    "https://github.com/alex-dukhno/async-native-tls.git",
    "https://github.com/sfackler/rust-native-tls.git",
    "https://github.com/ballista-compute/sqlparser-rs.git",
]
