[bans]
multiple-versions = "deny"

[licenses]
private = { ignore = true }
unlicensed = "deny"
confidence-threshold = 0.93
allow = [
    "Apache-2.0",
    "BSD-3-Clause",
    "MIT",
    "ISC",
    "PostgreSQL"
]

[sources]
unknown-git = "deny"
unknown-registry = "deny"
