[bans]
multiple-versions = "deny"
skip-tree = [
    { name = "rand" },
]

[licenses]
private = { ignore = true }
unlicensed = "deny"
confidence-threshold = 0.93
allow = [
    "Apache-2.0",
    "BSD-3-Clause",
    "MIT",
    "Zlib",
    "ISC",
    "PostgreSQL"
]
exceptions = [
    # smol use wepoll
    { allow = ["MPL-2.0"], name = "wepoll-sys" },
    { allow = ["MPL-2.0"], name = "colored" },
]

[sources]
unknown-git = "deny"
unknown-registry = "deny"
allow-git = [
    "https://github.com/alex-dukhno/async-native-tls.git",
    "https://github.com/sfackler/rust-native-tls.git",
]
