[bans]
multiple-versions = "deny"
skip-tree = [
    # protocol -> blocking
    # node -> smol -> blocking
    { name = "blocking" }
]

[licenses]
private = { ignore = true }
unlicensed = "deny"
confidence-threshold = 0.93
allow = [
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "MIT",
    "Zlib",
]
exceptions = [
    # smol use wepoll
    { allow = ["MPL-2.0"], name = "wepoll-sys-stjepang" },
]

[sources]
unknown-git = "deny"
unknown-registry = "deny"
