[package]
name = "ast"
version = "0.1.0"
authors = ["Alex Dukhno <alex.dukhno@icloud.com>"]
edition = "2018"
publish = false

[dependencies]
sqlparser = { version = "0.6.1", features = ["bigdecimal"] }
log = "0.4.11"
sql_model = { path = "../sql_model" }
ordered-float = "2.0.0"
bigdecimal = "0.1.2"
