[package]
name = "ast"
version = "0.1.0"
authors = ["Alex Dukhno <alex.dukhno@icloud.com>"]
edition = "2018"
publish = false

[dependencies]
meta_def = { path = "../meta_def" }
repr = { path = "../repr" }
types = { path = "../types" }

bigdecimal = { version = "0.2.0", features = ["string-only"] }
log = "0.4.11"
sqlparser = { git = "https://github.com/ballista-compute/sqlparser-rs.git", branch = "main", features = ["bigdecimal"] }
