[package]
name = "query_processing_type_inference"
version = "0.1.0"
authors = ["Alex Dukhno <alex.dukhno@icloud.com>"]
edition = "2018"
publish = false

[dependencies]
data_manipulation_untyped_tree_old = { path = "../../data_manipulation/untyped_tree_old" }
data_manipulation_typed_tree_old = { path = "../../data_manipulation/typed_tree_old" }
data_manipulation_operators = { path = "../../data_manipulation/operators" }
types_old = { path = "../../../types_old" }

bigdecimal = { version = "0.2.0", features = ["string-only"] }
log = "0.4"