[package]
name = "data_repr"
version = "0.1.0"
authors = ["Alex Dukhno <alex.dukhno@icloud.com>"]
edition = "2018"
publish = false

[dependencies]
binary = { path = "binary" }
scalar = { path = "scalar" }
