[package]
name = "protocol"
version = "0.1.0"
authors = ["Alex Dukhno <alex.dukhno@icloud.com>"]
edition = "2018"

[dependencies]
log = "0.4.8"
byteorder = "1.0"
bytes = "0.5"
futures = { version = "0.3.5", features = ["std"] }

[dev-dependencies]
async-std = { version = "1.6.0", features = ["attributes"] }
test_helpers = { path = "../test_helpers" }
