[package]
name = "entities"
version = "0.1.0"
authors = ["Alex Dukhno <alex.dukhno@icloud.com>"]
edition = "2018"
publish = false

[dependencies]
types = { path = "types" }
definition = { path = "definition" }