[package]
name = "read_query_planner"
version = "0.1.0"
authors = ["Alex Dukhno <alex.dukhno@icloud.com>"]
edition = "2018"
publish = false

[dependencies]
read_query_plan = { path = "../plan" }
data_manipulation_typed_queries = { path = "../../data_manipulation/typed_queries" }
data_manipulation_typed_tree = { path = "../../data_manipulation/typed_tree" }
catalog = { path = "../../catalog" }
