[package]
name = "data_manager"
version = "0.1.0"
authors = ["Alex Dukhno <alex.dukhno@icloud.com>"]
edition = "2018"
publish = false

[dependencies]
binary = { path = "../../../data/binary" }
data_definition_operations = { path = "../../../data_definition/operations" }
meta_def = { path = "../../../meta_def" }
repr = { path = "../../../entities/repr" }
sql_model = { path = "../../sql_model" }
storage = { path = "../storage" }
types = { path = "../../../entities/types" }

dashmap = "4.0.2"
log = "0.4.14"

[dev-dependencies]
backtrace = "0.3.56"
rstest = "0.6.4"
tempfile = "3.1.0"
