[package]
name = "scalar"
version = "0.1.0"
authors = ["Alex Dukhno <alex.dukhno@icloud.com>"]
edition = "2018"
publish = false

[dependencies]
binary = { path = "../../storage/binary" }
query_ast = { path = "../../postgres/query_ast" }
types = { path = "../entities/types" }

pg_wire_payload = "0.1.0"

bigdecimal = { version = "0.2.0", features = ["string-only"] }
