[package]
name = "sql_engine"
version = "0.1.0"
authors = ["Alex Dukhno <alex.dukhno@icloud.com>"]
edition = "2018"

[dependencies]
thiserror = "1.0.19"
log = "0.4.8"
core = { path = "../core" }
storage = { path = "../storage" }
sqlparser = { git = "https://github.com/andygrove/sqlparser-rs.git" }
bytes = "0.5"
test_helpers = { path = "../test_helpers" }
