[package]
name = "sql_engine"
version = "0.1.0"
authors = ["Alex Dukhno <alex.dukhno@icloud.com>"]
edition = "2018"
publish = false

[dependencies]
log = "0.4.8"
kernel = { path = "../kernel" }
storage = { path = "../storage" }
sqlparser = { version = "0.5.1", features = ["bigdecimal"] }
bigdecimal = "0.1.2"
ordered-float = "2.0.0"
sql_types = { path = "../sql_types" }
protocol = { path = "../protocol" }
futures-lite = "0.1.6"

[dev-dependencies]
rstest = "0.6.4"
