[package]
name = "pg_model"
version = "0.1.0"
authors = ["Alex Dukhno <alex.dukhno@icloud.com>"]
edition = "2018"
publish = false

[dependencies]
pg_wire = "0.5.0"

bigdecimal = { version = "0.2.0", features = ["string-only"] }
byteorder = "1.4.2"
rand = "0.8"

[dev-dependencies]
rstest = "0.6.4"
