[package]
name = "persistent"
version = "0.1.0"
authors = ["Alex Dukhno <alex.dukhno@icloud.com>"]
edition = "2018"
publish = false

[dependencies]
binary = { path = "../binary" }
storage_api = { path = "../api" }

sled = "0.34.6"
log = "0.4.14"
