[package]
name = "data_manipulation_query_plan"
version = "0.1.0"
authors = ["Alex Dukhno <alex.dukhno@icloud.com>"]
edition = "2018"
publish = false

[dependencies]
data_manipulation_typed_tree = { path = "../typed_tree" }
data_manipulation_typed_values = { path = "../typed_values" }
data_manipulation_query_result = { path = "../query_result" }
data_binary = { path = "../../data/binary" }
data_scalar = { path = "../../data/scalar" }
catalog = { path = "../../catalog" }
types = { path = "../../entities/types" }
definition = { path = "../../entities/definition" }
pg_result = { path = "../../../postgres/pg_result" }

bigdecimal = { version = "0.2.0", features = ["string-only"] }
log = "0.4.14"
