[package]
name = "data_manipulation_query_plan"
version = "0.1.0"
authors = ["Alex Dukhno <alex.dukhno@icloud.com>"]
edition = "2018"
publish = false

[dependencies]
data_manipulation_typed_tree_old = { path = "../typed_tree_old" }
data_manipulation_query_result = { path = "../query_result" }
binary = { path = "../../../data_repr/binary" }
definition = { path = "../../../definition" }
catalog = { path = "../../catalog" }
query_response = { path = "../../../postgre_sql/query_response" }
scalar = { path = "../../../data_repr/scalar" }
storage = { path = "../../../storage" }
types_old = { path = "../../../types_old" }

bigdecimal = { version = "0.2.0", features = ["string-only"] }
log = "0.4"
