[package]
name = "constraints"
version = "0.1.0"
authors = ["Alex Dukhno <alex.dukhno@icloud.com>"]
edition = "2018"
publish = false

[dependencies]
ast = { path = "../ast" }
repr = { path = "../repr" }
sql_model = { path = "../sql_model" }

bigdecimal = { version = "0.2.0", features = ["string-only"] }
num-bigint = "0.3"

[dev-dependencies]
rstest = "0.6.4"
