[package]
name = "query_analyzer_old"
version = "0.1.0"
authors = ["Alex Dukhno <alex.dukhno@icloud.com>"]
edition = "2018"
publish = false

[dependencies]
description = { path = "../description" }
meta_def = { path = "../../../meta_def" }
data_manager = { path = "../../catalog_deprecated/data_manager" }
types = { path = "../../../entities/types" }

pg_wire = "0.5.0"
sql_ast = { path = "../../../query_parsing/sql-ast" }

[dev-dependencies]

bigdecimal = { version = "0.2.0", features = ["string-only"] }
