[package]
name = "checked_queries"
version = "0.1.0"
authors = ["Alex Dukhno <alex.dukhno@icloud.com>"]
edition = "2018"

[dependencies]
definition = { path = "../../definition" }
checked_tree = { path = "../checked_tree" }
