[package]
name = "query_analyzer"
version = "0.1.0"
authors = ["Alex Dukhno <alex.dukhno@icloud.com>"]
edition = "2018"
publish = false

[dependencies]
description = { path = "../description" }
metadata = { path = "../metadata" }
sql_model = { path = "../sql_model" }

sqlparser = { git = "https://github.com/ballista-compute/sqlparser-rs.git", branch = "main", features = ["bigdecimal"] }

[dev-dependencies]
meta_def = { path = "../meta_def" }

bigdecimal = { version = "0.2.0", features = ["string-only"] }
