[package]
name = "query_planner"
version = "0.1.0"
authors = ["Alex Dukhno <alex.dukhno@icloud.com>"]
edition = "2018"
publish = false

[dependencies]
ast = { path = "../ast" }
constraints = { path = "../constraints" }
meta_def = { path = "../meta_def" }
data_definition = { path = "../data_definition" }
plan = { path = "../plan" }
types = { path = "../types" }

bigdecimal = { version = "0.2.0", features = ["string-only"] }
log = "0.4.11"
sqlparser = { git = "https://github.com/ballista-compute/sqlparser-rs.git", branch = "main", features = ["bigdecimal"] }

[dev-dependencies]
data_manager = { path = "../data_manager" }

rstest = "0.6.4"
