[package]
name = "validator"
version = "0.1.0"
authors = ["Alex Dukhno <alex.dukhno@icloud.com>"]
edition = "2018"
publish = false

[dependencies]
analysis_tree = { path = "../../annotated_tree" }
expr_operators = { path = "../../query_analysis/expr_operators" }
types = { path = "../../entities/types" }

bigdecimal = { version = "0.2.0", features = ["string-only"] }
log = "0.4.11"
