[package]
name = "data_manipulation_typed_queries"
version = "0.1.0"
authors = ["Alex Dukhno <alex.dukhno@icloud.com>"]
edition = "2018"
publish = false

[dependencies]
data_manipulation_typed_tree_old = { path = "../typed_tree_old" }
definition = { path = "../../../definition" }
