[package]
name = "storage"
version = "0.1.0"
authors = ["Alex Dukhno <alex.dukhno@icloud.com>"]
edition = "2018"
publish = false

[dependencies]
kernel = { path = "../kernel" }
log = "0.4.8"
sled = { version = "0.34.2", features = ["default"] }
sql_types = { path = "../sql_types" }
serde = { version = "1.0.114", features = ["derive"] }
bincode = "1.3.1"
representation = { path = "../representation" }
itertools = "0.9.0"
backtrace = "0.3.49"

[dev-dependencies]
rstest = "0.6.4"
tempfile = "3.1.0"
assert2 = "0.3.1"
