[package]
name = "storage"
version = "0.1.0"
authors = ["Alex Dukhno <alex.dukhno@icloud.com>"]
edition = "2018"
publish = false

[dependencies]
kernel = { path = "../kernel" }
log = "0.4.8"
sled = { version = "0.32.0", features = ["default"] }
sql_types = { path = "../sql_types" }
serde = { version = "1.0.114", features = ["derive"] }
bincode = "1.3.1"

[dev-dependencies]
backtrace = "0.3.49"
rstest = "0.6.4"
sql_engine = { path = "../sql_engine" }
