[package]
name = "executor"
version = "0.1.0"
authors = ["Alex Dukhno <alex.dukhno@icloud.com>"]
edition = "2018"
publish = false

[dependencies]
analysis_tree = {path = "../../annotated_tree" }
catalog = { path = "../../data/catalog" }

[dev-dependencies]
definition = { path = "../../entities/definition" }
