[package]
name = "executor"
version = "0.1.0"
authors = ["Alex Dukhno <alex.dukhno@icloud.com>"]
edition = "2018"
publish = false

[dependencies]
data_manipulation_annotated_queries = { path = "../../data_manipulation/annotated_queries" }
catalog = { path = "../../data/catalog" }

[dev-dependencies]
definition = { path = "../../entities/definition" }
