[package]
name = "write_query_executor"
version = "0.1.0"
authors = ["Alex Dukhno <alex.dukhno@icloud.com>"]
edition = "2018"
publish = false

[dependencies]
data_manipulation_typed_queries = { path = "../../data_manipulation/typed_queries" }
data_manipulation_typed_tree = { path = "../../data_manipulation/typed_tree" }
data_manipulation_query_result = { path = "../../data_manipulation/query_result" }
catalog = { path = "../../data/catalog" }

[dev-dependencies]
data_definition_operations = { path = "../../data_definition/operations" }
definition = { path = "../../entities/definition" }
types = { path = "../../entities/types" }
