[package]
name = "executor"
version = "0.1.0"
authors = ["Alex Dukhno <alex.dukhno@icloud.com>"]
edition = "2018"
publish = false

[dependencies]
annotated_tree = { path = "../../annotated_tree" }
data_manipulation_query_plan = { path = "../../data_manipulation/query_plan" }
catalog = { path = "../../data/catalog" }

[dev-dependencies]
definition = { path = "../../entities/definition" }
