[package]
name = "data_manipulation_operators"
version = "0.1.0"
authors = ["Alex Dukhno <alex.dukhno@icloud.com>"]
edition = "2018"
publish = false

[dependencies]
data_manipulation_query_result = { path = "../query_result" }
types_old = { path = "../../../types_old" }
query_ast = { path = "../../../postgre_sql/query_ast" }
scalar = { path = "../../../data_repr/scalar" }

bigdecimal = { version = "0.2.0", features = ["string-only"] }
regex = "1.4.3"
log = "0.4"

[dev-dependencies]
rstest = "0.10"
