[package]
name = "data_manipulation_untyped_tree_builder"
version = "0.1.0"
authors = ["Alex Dukhno <alex.dukhno@icloud.com>"]
edition = "2018"
publish = false

[dependencies]
definition = { path = "../../../definition" }
operators = { path = "../../../inter_reprs/operators" }
query_ast = { path = "../../../inter_reprs/query_ast" }
types = { path = "../../../types" }
untyped_tree = { path = "../../../inter_reprs/untyped_tree" }

bigdecimal = { version = "0.2.0", features = ["string-only"] }
