[package]
name = "definition_planner"
version = "0.1.0"
authors = ["Alex Dukhno <alex.dukhno@icloud.com>"]
edition = "2018"
publish = false

[dependencies]
catalog = { path = "../catalog" }
data_definition_execution_plan = { path = "../data_definition/execution_plan" }
definition = { path = "../entities/definition" }
query_ast = { path = "../../postgre_sql/query_ast" }
query_response = { path = "../../postgre_sql/query_response" }
storage = { path = "../../storage", features = ["in-memory"] }
types = { path = "../entities/types" }
