[package]
name = "test_helpers"
version = "0.1.0"
authors = ["Alex Dukhno <alex.dukhno@icloud.com>"]
edition = "2018"
publish = false

[dependencies]
async-std = { version = "1.6.2", features = ["attributes"] }
tempfile = "3.1.0"
storage = { path = "../storage" }
kernel = { path = "../kernel" }
byteorder = "1.3.4"
iobuf = { git = "https://github.com/alex-dukhno/iobuf.git", branch="compile-with-1.46.0-nightly" }

[dev-dependencies]
rstest = "0.6.4"
