[package]
name = "catalog"
version = "0.1.0"
authors = ["Alex Dukhno <alex.dukhno@icloud.com>"]
edition = "2018"
publish = false

[dependencies]
storage = { path = "../../storage/" }

data_definition_execution_plan = { path = "../data_definition/execution_plan" }
definition = { path = "../entities/definition" }
types = { path = "../entities/types" }

dashmap = "4.0.2"
log = "0.4.14"

[dev-dependencies]
rstest = "0.6.4"
