[package]
name = "node"
version = "0.1.0"
authors = ["Alex Dukhno <alex.dukhno@icloud.com>"]
edition = "2018"

[lib]
name = "node"

[[bin]]
name = "database"
path = "src/bin.rs"

[dependencies]
async-std = { version = "1.6.0", features = ["attributes"] }
core = { path = "../core" }
storage = { path = "../storage" }
protocol = { path = "../protocol" }
log = "0.4.8"
pretty_env_logger = "0.4.0"
sqlparser = { git = "https://github.com/andygrove/sqlparser-rs.git" }

[dev-dependencies]
bytes = "0.5"
postgres = "0.17.3"
test_helpers = { path = "../test_helpers" }
