[package]
name = "node"
version = "0.1.0"
authors = ["Alex Dukhno <alex.dukhno@icloud.com>"]
edition = "2018"
publish = false

[lib]
name = "node"

[[bin]]
name = "database"
path = "src/bin.rs"

[dependencies]
analysis = { path = "../analysis" }
binder = { path = "../binder" }
catalog = { path = "../catalog" }
connection = { path = "../connection" }
description = { path = "../description" }
data_manager = { path = "../data_manager" }
data_definition = { path = "../data_definition" }
parser = { path = "../parser" }
pg_model = { path = "../pg_model" }
plan = { path = "../plan" }
pg_wire = "0.5.0"
schema_planner = { path = "../schema_planner" }
schema_executor = { path = "../schema_executor" }
query_analyzer = { path = "../query_analyzer" }
query_analyzer_old = { path = "../query_analyzer_old" }
query_executor = { path = "../query_executor" }
query_planner = { path = "../query_planner" }
sql_model = { path = "../sql_model" }
types = { path = "../types" }

async-executor = "1.4.0"
async-dup = "1.2.1"
async-io = "1.3.1"
blocking = "1.0.0"
bigdecimal = { version = "0.2.0", features = ["string-only"] }
futures-lite = "1.11.3"
itertools = "0.10.0"
log = "0.4.8"
simple_logger = { version = "1.10.0" }
sqlparser = { git = "https://github.com/ballista-compute/sqlparser-rs.git", branch = "main", features = ["bigdecimal"] }

[dev-dependencies]
rstest = "0.6.4"
