name: Java Drivers Compatibility Tests

on:
  schedule:
    - cron: 0 0 * * 1 # weekly on Monday
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  impossibl-pgjdbc-ng-driver:
    container:
      image: ghcr.io/alex-dukhno/isomorphicdb:latest
      ports:
        - 5432:5432
      options:
        --network host
    runs-on: ubuntu-latest
    steps:
      - name: checkout impossibl/pgjdbc-ng
        uses: actions/checkout@v2
        with:
          repository: 'impossibl/pgjdbc-ng'
      - name: set-up-java
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: run pgjdbc-ng test suite
        run: ./gradlew -PnoDocker=true test
