name: Merge

on:
  push:
    branches: [ master ]

defaults:
  run:
    shell: bash

jobs:
  publish-docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build-&-push-docker-image
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: alex-dukhno/database/database
          tags: latest

  compatibility-tests:
    needs:
      - publish-docker
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12.4
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5433:5432
    steps:
      - name: docker-login
        run: echo ${{secrets.GITHUB_TOKEN}} | docker login docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: pull-docker-image
        run: docker pull "docker.pkg.github.com/alex-dukhno/database/database:latest"
      - name:
        run: docker run -it -d -p 5432:5432 docker.pkg.github.com/alex-dukhno/database/database:latest
      - name: checkout
        uses: actions/checkout@v2
      - name: install java
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: run-tests
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: test -Dci=true

  coverage:
    needs:
      - compatibility-tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install tarpaulin
        uses: actions-rs/install@v0.1
        with:
          crate: cargo-tarpaulin
          version: 0.14.0
          use-tool-cache: true
      - name: unit-tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all
      - name: code-coverage
        run: cargo tarpaulin -o Lcov --output-dir ./coverage
      - name: coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
