name: Merge

on:
  push:
    branches: [ main ]

defaults:
  run:
    shell: bash

jobs:
#  TODO: database is under massive rewrite. skipping building latest image as it
#        will contain broken engine
#  publish-docker:
#    runs-on: ubuntu-latest
#    steps:
#      - name: checkout
#        uses: actions/checkout@v2
#      - name: build-&-push-docker-image
#        uses: docker/build-push-action@v1
#        with:
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#          registry: docker.pkg.github.com
#          repository: alex-dukhno/isomorphicdb/isomorphicdb
#          tags: latest

  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install tarpaulin
        uses: actions-rs/install@v0.1
        with:
          crate: cargo-tarpaulin
          version: 0.16.0
          use-tool-cache: true
      - name: run code coverage
        run: cargo tarpaulin --ignore-tests -o Lcov --output-dir ./coverage
      - name: upload to coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
