name: pgjdbc driver

on:
  schedule:
    - cron: 0 0 1 * * # monthly

defaults:
  run:
    shell: bash

jobs:
  pgjdbc-pgjdbc-driver:
    runs-on: ubuntu-latest
    steps:
      - name: start IsomorphicDB docker container
        run: |
          docker run -it -d --network host -p 5432:5432 ghcr.io/alex-dukhno/isomorphicdb
          echo 'CONTAINER_ID='$(docker ps -q) >> $GITHUB_ENV
      - name: checkout pgjdbc/pgjdbc repository
        uses: actions/checkout@v2
        with:
          repository: 'pgjdbc/pgjdbc'
      - name: set-up-java
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: run pgjdbc test suite
        run: ./gradlew test
      - name: stop IsomorphicDB docker container
        run: docker stop ${{ env.CONTAINER_ID }}
