name: psycopg2 driver

on:
  schedule:
    - cron: 0 0 * * 1 # weekly on Monday
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  pgjdbc-pgjdbc-driver:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.6, 3.7, 3.8 ]
    steps:
      - name: start IsomorphicDB docker container
        run: |
          docker run -it -d --network host -p 5432:5432 ghcr.io/alex-dukhno/isomorphicdb
          echo 'CONTAINER_ID='$(docker ps -q) >> $GITHUB_ENV
      - name: checkout pgjdbc/pgjdbc repository
        uses: actions/checkout@v2
        with:
          repository: 'psycopg/psycopg2'
      - name: set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: install dependencies
        run: sudo apt-get install -y libpq-dev
      - name: run psycopg2 test suite
        run: |
          PSYCOPG2_TESTDB=test PSYCOPG2_TESTDB_HOST=localhost PSYCOPG2_TESTDB_PORT=5432 PSYCOPG2_TESTDB_USER=postgres python setup.py build
          PSYCOPG2_TESTDB=test PSYCOPG2_TESTDB_HOST=localhost PSYCOPG2_TESTDB_PORT=5432 PSYCOPG2_TESTDB_USER=postgres python setup.py install
          PSYCOPG2_TESTDB=test PSYCOPG2_TESTDB_HOST=localhost PSYCOPG2_TESTDB_PORT=5432 PSYCOPG2_TESTDB_USER=postgres python -c "import tests; tests.unittest.main(defaultTest='tests.test_suite')" --verbose
      - name: stop IsomorphicDB docker container
        run: docker stop ${{ env.CONTAINER_ID }}
