name: Pull Requests

on:
  pull_request:
    branches: [ main ]

env:
  RUSTFLAGS: -Dwarnings
  RUST_BACKTRACE: 1

defaults:
  run:
    shell: bash

jobs:
  cargo-deny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: EmbarkStudios/cargo-deny-action@v1

  rustfmt:
    needs: cargo-deny
    name: rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: set-up-rust
        uses: hecrj/setup-rust-action@v1
        with:
          components: rustfmt
          rust-version: nightly
      - uses: actions/checkout@v2
      - run: ./ci/rustfmt.sh

  clippy:
    needs:
      - cargo-deny
      - rustfmt
    name: clippy
    runs-on: ubuntu-latest
    steps:
      - name: set-up-rust
        uses: hecrj/setup-rust-action@v1
        with:
          components: clippy
          rust-version: stable
      - uses: actions/checkout@v2
      - run: ./ci/clippy.sh

  tests:
    needs:
      - cargo-deny
      - rustfmt
      - clippy
    strategy:
      matrix:
        os:
          - ubuntu
          - windows
          - macos
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install tarpaulin
        if: matrix.os == 'ubuntu'
        uses: actions-rs/install@v0.1
        with:
          crate: cargo-tarpaulin
          version: 0.14.0
          use-tool-cache: true
      - name: unit-tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all
      - name: code-coverage
        if: matrix.os == 'ubuntu'
        run: cargo tarpaulin -o Lcov --output-dir ./coverage
      - name: coveralls
        if: matrix.os == 'ubuntu'
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  compatibility-test:
    needs:
      - cargo-deny
      - rustfmt
      - clippy
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12.4
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5433:5432
    steps:
      - name: set-up-rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable
      - name: set-up-java
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: checkout
        uses: actions/checkout@v2
      - name: start-database
        run: cargo run & cargo build && sleep 1
      - name: run-tests
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: test -Dci=true

  erlang-client-compatibility:
    needs:
      - cargo-deny
      - rustfmt
      - clippy
    runs-on: ubuntu-latest
    steps:
      - name: set-up-rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable
      - name: set-up-erlang
        uses: gleam-lang/setup-erlang@v1.1.0
        with:
            otp-version: 23.1
      - name: checkout
        uses: actions/checkout@v2
      - name: run-tests
        run: ./ci/erlang_client.sh

  ci-success:
    name: ci
    if: github.event_name == 'push' && success()
    needs:
      - tests
      - rustfmt
      - clippy
    runs-on: ubuntu-latest
    steps:
      - name: Mark the job as a success
        run: exit 0

  ci-failure:
    name: ci
    if: github.event_name == 'push' && !success()
    needs:
      - tests
      - rustfmt
      - clippy
    runs-on: ubuntu-latest
    steps:
      - name: Mark the job as a failure
        run: exit 1
