name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  RUSTFLAGS: -Dwarnings
  RUST_BACKTRACE: 1

defaults:
  run:
    shell: bash

jobs:
  cargo-deny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: EmbarkStudios/cargo-deny-action@v1

  all-tests:
    strategy:
      matrix:
        os:
          - ubuntu
          - windows
          - macos
    runs-on: ${{ matrix.os }}-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: toolchain
      uses: actions-rs/toolchain@v1
    - name: install tarpaulin
      if: matrix.os == 'ubuntu'
      uses: actions-rs/install@v0.1
      with:
        crate: cargo-tarpaulin
        version: 0.14.0
        use-tool-cache: true
    - name: unit-tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --lib --all
    - name: integration-tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --tests integration_sql -- --nocapture
    - name: code-coverage
      if: matrix.os == 'ubuntu'
      run: cargo tarpaulin -o Lcov --output-dir ./coverage
    - name: coveralls
      if: matrix.rust == 'ubuntu'
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

  rustfmt:
    name: rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@v1
      - name: rustfmt
        run: ./ci/rustfmt.sh

  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@v1
      - name: clippy
        run: ./ci/clippy.sh

  ci-success:
    name: ci
    if: github.event_name == 'push' && success()
    needs:
      - all-tests
      - rustfmt
      - clippy
    runs-on: ubuntu-latest
    steps:
      - name: Mark the job as a success
        run: exit 0

  ci-failure:
    name: ci
    if: github.event_name == 'push' && !success()
    needs:
      - all-tests
      - rustfmt
      - clippy
    runs-on: ubuntu-latest
    steps:
      - name: Mark the job as a failure
        run: exit 1
