[package]
name = "sql_types"
version = "0.1.0"
authors = ["Alex Dukhno <alex.dukhno@icloud.com>"]
edition = "2018"
publish = false

[dependencies]
kernel = { path = "../kernel" }
lexical = "5.2.0"
rstest = "0.6.4"
